### ISSUE TITLE
Begin accumulating data to fill tables

### ISSUE THREAD

**Issue by ghost** [daveyjonezz/Project2#10]
How many kinds of devices are we using?
1. fitbit
2. mobile phone apps (apple and android)?
3. manual intake through front end
4. raspberry pi?

**Comment by ghost** [comment]
ignore old comment; project topic has changed. please google dummy data sets (or create them) so we have tables we can test.

**Comment by ghost** [comment]
Please update DB with yourself as a user; Davis, please upload working DB model. These are our tables; the data on weather events will need to be dummy copy.

**Comment by ghost** [comment]
Please update the database with yourself as a user. We're integrating weather events in a different way, and currently not as part of the DB.

**Comment by jenshin75** [comment]
i registered myself as a new user after after heroku
