### ISSUE TITLE
Try out and config IoT sensors to RPi

### ISSUE THREAD

**Issue by Mari0203** [daveyjonezz/Project2#14]

**Comment by ghost** [comment]
this is in mari's and susan's(yes/no?) court; please update us on whether this can be used as a water sensor and what the conversion of data from the cloud to our server needs to be.

**Comment by Sooze16** [comment]
I have RPi up and working.  Utilizing breadboard and external led and cords with raw ends that should short and relay a sensor... Do not know how this will get to the Twilio to trigger an alarm.  Samsung sensor is here...wifi equipt...this may be a better solution.

**Comment by ghost** [comment]
Susan, please discuss with Mari. More sensors aren't necessarily a bad thing, especially if we're demo-ing in real-time during the presentation.
