### ISSUE TITLE
Testing-data collection and pull from IoT/RPi to MySQL dbs.

### ISSUE THREAD

**Issue by Mari0203** [daveyjonezz/Project2#47]
Testing-data collection and pull from IoT/RPi to MySQL dbs for integration

**Comment by ghost** [comment]
please discuss this with Davis and Susan. They may have already solved it.

**Comment by ghost** [comment]
Mari is currently working on this issue; it involves python and she has communicated that it may take some time.

**Comment by ghost** [comment]
mari and phil made this work.
