### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by ghost** [daveyjonezz/Project2#59]
Susan has begun the document. We should all be reviewing and adding to it as needed.

**Comment by jenshin75** [comment]
done - corrected path to logos/flow.  additional changes to flow should auto update as long as there is no change to file name.

**Comment by ghost** [comment]
replaced flow diagram with updated version; added additional language regarding purpose and use of product. added tech. waiting for mari to review.

**Comment by ghost** [comment]
mari and i checked for accuracy last night and made a few edits. should reflect final project accurately.
