### ISSUE TITLE
UX/UI Fine-tuning

### ISSUE THREAD

**Issue by ghost** [daveyjonezz/Project2#62]
Need to lock down the grid structure and prevent things from jumping around. Need to figure out the box-shadow CSS; currently not working. Need to rework moment.js so that it populates the correct div with image. Need to figure out adding background image to login page without disrupting everything already in place.

**Comment by jenshin75** [comment]
have background color working in login page without disrupting everything else in place.  we can replace color with image but here's what needs to be add in a nutshell - 

views/index.handlebar - add LOGINBOX on line 205 as such:
<div class="text-center loginbox" >

public/assets/styles/styles.css - add these:

 div.loginbox{
  background-color: aqua;  //this can be replaced with url instead
  height: 100vh;  //this will make the login page take up 100% of the screen and center
 }

 .loginbox a {
 top: 50%;
 position: absolute;
 translate: transformY(-50%);
 transform: translateY(-50%);
 }

**Comment by ghost** [comment]
input in document

**Comment by jenshin75** [comment]
updated index/main login page to show falcon tiles

**Comment by ghost** [comment]
restyled login button, but needs to centered?? restyled weather box, but both tabs populate initially and is defaulting to hardcode despite login; redeveloped site diagram; green glow is on; moment not working again.

**Comment by ghost** [comment]
waether tabe were fixed based on api/package/script re-sort with isabel. see note regarding weather feed and need to advance for loop to begin at [2]
