### ISSUE TITLE
Weather package and API

### ISSUE THREAD

**Issue by ghost** [daveyjonezz/Project2#63]
Susan is working on getting the Current Conditions to display inside the main image. The drill-down if an alert button is triggered, eg flooding, would be a replica page with the flood image as the background and the weather info modal with multiple tabs to display future forecasts.

**Comment by Sooze16** [comment]
The modal has been updated.  Used the configuration provided by Madeleine.  Data is filling in on the current and forecast tabs.  UI/UX needs to adjust this in the grey area on the screen.  Cookies have been added so the conditions for the correct zip code will display.

**Comment by ghost** [comment]
redeveloped format as modal disappears after you click elsewhere. is now a list on tabs. we may have some conflicting code? theres the npm package; a script; another script in the indexroutes that actually created the data object. not sure what's doing what at this point.

**Comment by ghost** [comment]
isabel helped me sort this out so we have the data object being built in the right place. it requires advancing the for loop to pull the correct day for future forecast. i have forked this repo and it is working correctly on my own version of HORUS. please lmk if need further info.
